// screens/ReportDetail/styles.js
import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  reportCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  reportHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1F2937",
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  locationText: {
    fontSize: 15,
    color: "#4B5563",
    marginLeft: 6,
  },
  description: {
    fontSize: 16,
    color: "#4B5563",
    lineHeight: 24,
    marginBottom: 16,
  },
  imageContainer: {
    alignItems: "center",
    marginBottom: 8,
  },
  imagePlaceholder: {
    width: "100%",
    height: 200,
    backgroundColor: "#F3F4F6",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  imagePlaceholderText: {
    marginTop: 8,
    color: "#9CA3AF",
    fontSize: 14,
  },
  updateContainer: {
    flexDirection: "row",
    marginBottom: 20,
    alignItems: "center",
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 24,
    padding: 14,
    fontSize: 16,
    backgroundColor: "#FFFFFF",
  },
  sendButton: {
    backgroundColor: "#000000",
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },
  sendButtonDisabled: {
    backgroundColor: "#9CA3AF",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 12,
    marginTop: 24,
  },
  emptyUpdateContainer: {
    alignItems: "center",
    padding: 24,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginBottom: 16,
  },
  emptyListText: {
    textAlign: "center",
    color: "#6B7280",
    marginTop: 8,
    fontSize: 16,
  },
  updateItem: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  updateText: {
    fontSize: 16,
    color: "#1F2937",
    marginBottom: 8,
    lineHeight: 22,
  },
  updateTimestamp: {
    fontSize: 12,
    color: "#6B7280",
  },
  selectLinesmenButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 14,
    backgroundColor: "#FFFFFF",
    marginBottom: 12,
  },
  selectLinesmenButtonText: {
    fontSize: 16,
    color: "#000000",
    fontWeight: "500",
  },
  selectedLinesmenContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  selectedLinesman: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    padding: 8,
    paddingRight: 12,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  userIcon: {
    marginRight: 6,
  },
  selectedLinesmanText: {
    fontSize: 14,
    color: "#1F2937",
    marginRight: 8,
  },
  noLinesmenContainer: {
    padding: 24,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  noLinesmenText: {
    color: "#6B7280",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: width * 0.85,
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1F2937",
  },
  linesmanItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  linesmanInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  linesmanIcon: {
    marginRight: 12,
  },
  linesmanItemText: {
    fontSize: 16,
    color: "#1F2937",
  },
  selectedLinesmanItem: {
    backgroundColor: "#F3F4F6",
  },
  uncheckedCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#D1D5DB",
  },
  doneButton: {
    backgroundColor: "#000000",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  doneButtonText: {
    fontSize: 16,
    color: "white",
    fontWeight: "600",
  },
});

export default styles;
